name: camion
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  connectivity_plus: ^5.0.1
  flutter_screenutil: ^5.6.0
  http: ^1.1.0
  equatable: ^2.0.5
  shared_preferences: ^2.1.0
  flutter_svg: ^2.0.9
  dropdown_button2: ^2.1.4
  image_picker: ^1.0.4
  file_picker: ^4.2.0
  shimmer: ^2.0.0
  google_fonts: ^6.1.0
  intl: ^0.18.1
  hexcolor: ^3.0.1
  like_button: ^2.0.5
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.8
  cached_network_image: ^3.2.3
  flutter_img: ^0.1.5+111
  timeline_tile: ^2.0.0
  ensure_visible_when_focused: ^1.2.0
  popover: ^0.2.8
  provider:
  percent_indicator: ^4.0.1
  easy_splash_screen: ^1.0.4
  google_maps_flutter: ^2.5.0
  flutter_typeahead: ^4.6.2
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  flutter_polyline_points: ^2.0.0
  location: ^5.0.3
  flutter_stripe: ^8.0.0
  cloud_firestore: ^4.14.0
  timelines: ^0.1.0
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/style/
    - assets/.env
    - lang/

